sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image for go client
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd go && make docker-build docker-push